"""HTML 看板生成模块"""
from __future__ import annotations
import json
from datetime import datetime
from collections import defaultdict


def generate_dashboard_html(records: list[dict], stats: dict, profile_name: str = "Paper Hunter") -> str:
    """生成 HTML 看板页面"""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total = stats.get("total", len(records))
    by_label = stats.get("by_label", {})
    core_count = by_label.get("core", 0)
    strong_count = by_label.get("strongly_related", 0)

    # 年份分布
    by_year: dict[int, int] = defaultdict(int)
    for r in records:
        by_year[r.get("year", 0)] += 1
    years = sorted(by_year.keys(), reverse=True)[:10]
    year_labels = json.dumps([str(y) for y in years])
    year_data = json.dumps([by_year[y] for y in years])

    # 主题分布
    topic_counts: dict[str, int] = defaultdict(int)
    for r in records:
        for t in r.get("topics", []):
            topic_counts[t] += 1
    top_topics = sorted(topic_counts.items(), key=lambda x: -x[1])[:8]
    topic_labels = json.dumps([t[0] for t in top_topics])
    topic_data = json.dumps([t[1] for t in top_topics])

    # 最新核心论文
    core_papers = [r for r in records if r.get("quality_label") == "core"]
    core_papers.sort(key=lambda r: (-r.get("year", 0), -r.get("relevance_score", 0)))
    latest_core = core_papers[:10]

    core_rows = ""
    for p in latest_core:
        title = p.get("title", "")[:50]
        url = p.get("url", "#")
        year = p.get("year", "")
        score = p.get("relevance_score", 0)
        cit = p.get("citation_count", 0)
        summary = p.get("summary_zh", p.get("one_line_summary", ""))[:60]
        core_rows += f'<tr><td><a href="{url}" target="_blank">{title}</a></td><td>{year}</td><td>{score}</td><td>{cit}</td><td>{summary}</td></tr>\n'

    html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{profile_name} - Dashboard</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }}
.container {{ max-width: 1200px; margin: 0 auto; }}
h1 {{ color: #333; text-align: center; }}
.stats {{ display: flex; gap: 20px; justify-content: center; margin: 20px 0; }}
.stat-card {{ background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); text-align: center; min-width: 150px; }}
.stat-number {{ font-size: 2em; font-weight: bold; color: #2196F3; }}
.stat-label {{ color: #666; margin-top: 5px; }}
.charts {{ display: flex; gap: 20px; margin: 20px 0; flex-wrap: wrap; }}
.chart-card {{ background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); flex: 1; min-width: 300px; }}
table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
th {{ background: #2196F3; color: white; }}
tr:hover {{ background: #f5f5f5; }}
a {{ color: #2196F3; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
.footer {{ text-align: center; color: #999; margin-top: 40px; padding: 20px; }}
</style>
</head>
<body>
<div class="container">
<h1>📚 {profile_name}</h1>
<p style="text-align: center; color: #666;">最后更新: {now}</p>

<div class="stats">
<div class="stat-card">
<div class="stat-number">{total}</div>
<div class="stat-label">论文总数</div>
</div>
<div class="stat-card">
<div class="stat-number">{core_count}</div>
<div class="stat-label">核心论文</div>
</div>
<div class="stat-card">
<div class="stat-number">{strong_count}</div>
<div class="stat-label">高相关论文</div>
</div>
</div>

<div class="charts">
<div class="chart-card">
<h3>📅 年份分布</h3>
<canvas id="yearChart" height="200"></canvas>
</div>
<div class="chart-card">
<h3>🔥 主题分布</h3>
<canvas id="topicChart" height="200"></canvas>
</div>
</div>

<h2>🔥 最新核心论文</h2>
<table>
<thead>
<tr><th>标题</th><th>年份</th><th>分数</th><th>引用</th><th>摘要</th></tr>
</thead>
<tbody>
{core_rows}
</tbody>
</table>

<div class="footer">
🤖 Auto-generated by <a href="https://github.com/MSWEIMZ/paper-hunter">Paper Hunter</a>
</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
const yearCtx = document.getElementById('yearChart').getContext('2d');
new Chart(yearCtx, {{
type: 'bar',
data: {{
labels: {year_labels},
datasets: [{{ label: '论文数', data: {year_data}, backgroundColor: '#2196F3' }}]
}},
options: {{ responsive: true, plugins: {{ legend: {{ display: false }} }} }}
}});

const topicCtx = document.getElementById('topicChart').getContext('2d');
new Chart(topicCtx, {{
type: 'doughnut',
data: {{
labels: {topic_labels},
datasets: [{{ data: {topic_data}, backgroundColor: ['#2196F3','#4CAF50','#FF9800','#F44336','#9C27B0','#00BCD4','#FF5722','#795548'] }}]
}},
options: {{ responsive: true }}
}});
</script>
</body>
</html>'''
    return html
