"""通知模块（支持飞书 webhook）"""
from __future__ import annotations
import json
import os
from urllib.request import urlopen, Request


def _get_webhook(env_name: str) -> str:
    """从环境变量获取 webhook URL"""
    return os.environ.get(env_name, "")


def _send_feishu_card(card: dict, webhook_url: str) -> bool:
    """发送飞书卡片消息"""
    if not webhook_url:
        print("  [INFO] 未配置 webhook，跳过通知")
        return False
    try:
        data = json.dumps(card, ensure_ascii=False).encode("utf-8")
        req = Request(webhook_url, data=data, headers={"Content-Type": "application/json"})
        with urlopen(req, timeout=10) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            if result.get("code") == 0 or result.get("StatusCode") == 0:
                return True
            print(f"  [WARN] 飞书返回: {result}")
            return False
    except Exception as e:
        print(f"  [WARN] 飞书通知失败: {e}")
        return False


def _build_feishu_card(
    profile_name: str,
    new_papers: list[dict],
    stats: dict,
    errors: list[str] | None = None,
) -> dict:
    """构建飞书卡片消息"""
    total = stats.get("total", 0)
    by_label = stats.get("by_label", {})
    core_count = by_label.get("core", 0)
    strong_count = by_label.get("strongly_related", 0)

    if errors:
        header_color = "red"
        title = f"❌ {profile_name} — 搜索出错"
        elements = [
            {"tag": "markdown", "content": "\n".join(f"• {e}" for e in errors)}
        ]
    elif not new_papers:
        header_color = "grey"
        title = f"📋 {profile_name} — 今日无新增"
        elements = [
            {"tag": "markdown", "content": f"**总论文数**: {total}\n**核心**: {core_count} | **高相关**: {strong_count}"},
        ]
    else:
        header_color = "green"
        title = f"📚 {profile_name} — 新增 {len(new_papers)} 篇论文"
        paper_lines = []
        for p in new_papers[:10]:
            label_icon = {"core": "🔥", "strongly_related": "📎"}.get(p.get("quality_label", ""), "📝")
            title_text = p.get("title", "")[:50]
            url = p.get("url", "#")
            authors = ", ".join(p.get("authors", [])[:2])
            score = p.get("relevance_score", 0)
            cit = p.get("citation_count", 0)
            venue = p.get("venue", "")
            summary = p.get("summary_zh", "")[:60]
            line = f"{label_icon} [{title_text}]({url})\n"
            line += f"  作者: {authors} | 分数: {score} | 引用: {cit}"
            if venue:
                line += f" | 会议: {venue}"
            if summary:
                line += f"\n  📝 {summary}"
            paper_lines.append(line)
        content = f"**总论文数**: {total} | 核心: {core_count} | 高相关: {strong_count}\n\n"
        content += "\n\n".join(paper_lines)
        if len(new_papers) > 10:
            content += f"\n\n... 还有 {len(new_papers) - 10} 篇"
        elements = [{"tag": "markdown", "content": content}]

    return {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {"tag": "plain_text", "content": title},
                "template": header_color,
            },
            "elements": elements,
        },
    }


def send_notification(
    profile_name: str,
    new_papers: list[dict],
    stats: dict,
    webhook_env: str = "",
    errors: list[str] | None = None,
) -> bool:
    """发送通知（入口函数）"""
    if not webhook_env:
        print("  [INFO] 未配置 webhook_env，跳过通知")
        return False
    webhook_url = _get_webhook(webhook_env)
    if not webhook_url:
        print(f"  [INFO] 环境变量 {webhook_env} 未设置，跳过通知")
        return False
    card = _build_feishu_card(profile_name, new_papers, stats, errors)
    return _send_feishu_card(card, webhook_url)


def _build_email_html(
    profile_name: str,
    new_papers: list[dict],
    stats: dict,
) -> str:
    """构建邮件 HTML 内容"""
    total = stats.get("total", 0)
    by_label = stats.get("by_label", {})
    core_count = by_label.get("core", 0)

    paper_rows = ""
    for p in new_papers[:20]:
        label = {"core": "🔥", "strongly_related": "📎"}.get(p.get("quality_label", ""), "📝")
        title = p.get("title", "")[:50]
        url = p.get("url", "#")
        authors = ", ".join(p.get("authors", [])[:2])
        score = p.get("relevance_score", 0)
        summary = p.get("summary_zh", "")[:60]
        paper_rows += f"<tr><td>{label}</td><td><a href='{url}'>{title}</a></td><td>{authors}</td><td>{score}</td><td>{summary}</td></tr>"

    return f"""
    <html>
    <body style='font-family: sans-serif; padding: 20px;'>
    <h2>📚 {profile_name} — 新增 {len(new_papers)} 篇论文</h2>
    <p>总论文数: {total} | 核心: {core_count}</p>
    <table border='1' cellpadding='8' cellspacing='0' style='border-collapse: collapse;'>
    <tr style='background: #2196F3; color: white;'>
        <th>标签</th><th>标题</th><th>作者</th><th>分数</th><th>摘要</th>
    </tr>
    {paper_rows}
    </table>
    <p style='color: #999; margin-top: 20px;'>🤖 Auto-generated by Paper Hunter</p>
    </body>
    </html>
    """


def send_email_notification(
    profile_name: str,
    new_papers: list[dict],
    stats: dict,
    smtp_host: str = "",
    smtp_port: int = 587,
    smtp_user: str = "",
    smtp_password: str = "",
    to_email: str = "",
) -> bool:
    """发送邮件通知

    Args:
        profile_name: 配置名称
        new_papers: 新增论文列表
        stats: 统计信息
        smtp_host: SMTP 服务器
        smtp_port: SMTP 端口
        smtp_user: 发件人邮箱
        smtp_password: 发件人密码
        to_email: 收件人邮箱

    Returns:
        是否发送成功
    """
    if not all([smtp_host, smtp_user, smtp_password, to_email]):
        print("  [INFO] 邮件配置不完整，跳过邮件通知")
        return False

    try:
        import smtplib
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"📚 {profile_name} — 新增 {len(new_papers)} 篇论文"
        msg["From"] = smtp_user
        msg["To"] = to_email

        html = _build_email_html(profile_name, new_papers, stats)
        msg.attach(MIMEText(html, "html", "utf-8"))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(msg)

        print(f"  ✅ 邮件通知已发送至 {to_email}")
        return True
    except Exception as e:
        print(f"  [WARN] 邮件发送失败: {e}")
        return False


def _build_telegram_message(
    profile_name: str,
    new_papers: list[dict],
    stats: dict,
) -> str:
    """构建 Telegram 消息文本"""
    total = stats.get("total", 0)
    by_label = stats.get("by_label", {})
    core_count = by_label.get("core", 0)

    if not new_papers:
        return f"📋 {profile_name} — 今日无新增论文\n总论文数: {total} | 核心: {core_count}"

    lines = [f"📚 {profile_name} — 新增 {len(new_papers)} 篇论文"]
    lines.append(f"总论文数: {total} | 核心: {core_count}")
    lines.append("")

    for p in new_papers[:10]:
        label = {"core": "🔥", "strongly_related": "📎"}.get(p.get("quality_label", ""), "📝")
        title = p.get("title", "")[:50]
        url = p.get("url", "")
        score = p.get("relevance_score", 0)
        cit = p.get("citation_count", 0)
        summary = p.get("summary_zh", "")[:40]

        line = f"{label} {title}\n  Score: {score} | Citations: {cit}"
        if url:
            line += f"\n  {url}"
        if summary:
            line += f"\n  📝 {summary}"
        lines.append(line)
        lines.append("")

    if len(new_papers) > 10:
        lines.append(f"... 还有 {len(new_papers) - 10} 篇")

    return "\n".join(lines)


def send_telegram_notification(
    profile_name: str,
    new_papers: list[dict],
    stats: dict,
    bot_token: str = "",
    chat_id: str = "",
) -> bool:
    """发送 Telegram 通知

    Args:
        profile_name: 配置名称
        new_papers: 新增论文列表
        stats: 统计信息
        bot_token: Telegram Bot Token
        chat_id: Telegram Chat ID

    Returns:
        是否发送成功
    """
    if not bot_token or not chat_id:
        print("  [INFO] Telegram 配置不完整，跳过通知")
        return False

    message = _build_telegram_message(profile_name, new_papers, stats)

    try:
        import json as _json
        url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
        payload = _json.dumps({
            "chat_id": chat_id,
            "text": message,
            "disable_web_page_preview": True,
        }).encode("utf-8")

        req = Request(url, data=payload, headers={"Content-Type": "application/json"})
        with urlopen(req, timeout=10) as resp:
            result = _json.loads(resp.read().decode("utf-8"))
            if result.get("ok"):
                print(f"  ✅ Telegram 通知已发送")
                return True
            print(f"  [WARN] Telegram 返回: {result}")
            return False
    except Exception as e:
        print(f"  [WARN] Telegram 通知失败: {e}")
        return False
